### ISSUE TITLE
Đặc Tả usecase

### ISSUE THREAD

**Issue by DoNguyenTanLinh** [HiImLeVanAnhDuc/TalkDesk_Clone_Nhom19#10]
- [x]  Đặc tả chức năng đăng nhập, đăng ký
- [x]  Đặc tả chức năng đăng xuất, quên mật khẩu
- [x]  Đặc tả chức năng tìm kiếm
- [x]  Đặc tả chức năng option
- [x]  Đặc tả chức năng liên hệ

**Comment by Ahringonmoto** [comment]
[milestone2.docx](https://github.com/HiImLeVanAnhDuc/TalkDesk_Clone_Nhom19/files/11070970/milestone2.docx)

**Comment by DoNguyenTanLinh** [comment]
[Đặc tả ĐN_Đk.docx](https://github.com/HiImLeVanAnhDuc/TalkDesk_Clone_Nhom19/files/11080851/D.c.t.DN_Dk.docx)
